#!/usr/bin/env python3

"""
Generate Asymptote source files for Open Graph images.

Input:
    generated/homepage.json

Template:
    scripts/og/og_template.asy

Output:
    generated/og/<source-directory>/<source>.asy

Examples:

    fgt/lec1.typ
        →
    generated/og/fgt/lec1.asy

    gt/lec2.typ
        →
    generated/og/gt/lec2.asy

    olympiad/ioqm/ioqm2024.typ
        →
    generated/og/olympiad/ioqm/ioqm2024.asy

    mopss/mopss_aug08.typ
        →
    generated/og/mopss/mopss_aug08.asy

Rules:

    1. Every content entry with a valid `.typ` source is
       considered eligible for automatic OG generation.

    2. If the entry explicitly provides `og_image`, no
       generated `.asy` file is created. The supplied image
       is assumed to be managed separately.

    3. The source directory structure is preserved under
       generated/og/.

    4. The `.typ` extension is replaced by `.asy`.

Therefore:

    source:
        foo/bar/example.typ

    generated:
        generated/og/foo/bar/example.asy
"""

import json
from pathlib import Path

from scripts.config import (
    ROOT,
    HOMEPAGE_JSON,
    GENERATED_OG_DIR,
    OG_TEMPLATE_FILE,
)

from scripts.site_config import (
    REPO_NAME, 
    GITHUB_USERNAME, 
    ASY_TOP_SECTION, 
    ASY_TARGET_EXAM,
    ASY_MOCKTITLE_A,
    ASY_MOCKTITLE_B,
    ASY_MOCKCARD_TOPIC,
    ASY_DEFAULT_MOCKCARD_TOPIC,
    ASY_DEFAULT_TOP_SECTION,
    ASY_DEFAULT_TARGET_EXAM,
    ASY_DEFAULT_MOCKTITLE_A,
    ASY_DEFAULT_MOCKTITLE_B,
    ASY_DEFAULT_NARRATIVE,
    )

# ============================================================
# Files used by Open Graph source generation
# ============================================================

# ------------------------------------------------------------
# Generated metadata
#
# The metadata is generated by the main metadata-generation
# stage and contains information about all website pages.
#
# Example:
#
#     generated/homepage.json
# ------------------------------------------------------------



# ------------------------------------------------------------
# Generated OG source directory
#
# All generated .asy files are stored here while preserving
# the directory structure of their corresponding source files.
#
# Example:
#
#     content/gt/lec1.typ
#             ↓
#     generated/og/gt/lec1.asy
# ------------------------------------------------------------


# ============================================================
# Utilities
# ============================================================

def escape_asy_string(value):
    """
    Escape a Python value for use inside an Asymptote string.

    In particular:

        \  →  \\

        "  →  \"

    This prevents metadata containing quotes or backslashes
    from breaking the generated Asymptote source.
    """

    return (
        str(value)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
    )


# ============================================================
# Generate one Asymptote source
# ============================================================

def generate_asy(
    template,
    *,
    number,
    title,
    category,
    file,
    tags,
    narrative,
    top_section,
    target_exam,
    mocktitle_a,
    mocktitle_b,
    mockcard_topic,
):
    """
    Generate one Asymptote source from content metadata.

    The template contains placeholders such as:

        __LECTURE_NUMBER__
        __TITLE__
        __CATEGORY__
        __FILE__
        __TAGS__

    which are replaced with escaped metadata values.
    """

    source = template

    # --------------------------------------------------------
    # Lecture/page number
    # --------------------------------------------------------

    source = source.replace(
        "__LECTURE_NUMBER__",
        escape_asy_string(number),
    )

    # --------------------------------------------------------
    # Page title
    # --------------------------------------------------------

    source = source.replace(
        "__TITLE__",
        escape_asy_string(title),
    )

    # --------------------------------------------------------
    # Category name
    # --------------------------------------------------------

    source = source.replace(
        "__CATEGORY__",
        escape_asy_string(category),
    )

    # --------------------------------------------------------
    # File name
    # --------------------------------------------------------

    source = source.replace(
        "__FILE__",
        escape_asy_string(file),
    )

    # --------------------------------------------------------
    # Tags
    # --------------------------------------------------------

    tag_text = " · ".join(tags)

    source = source.replace(
        "__TAGS__",
        escape_asy_string(tag_text),
    )

    
    # --------------------------------------------------------
    # Narrative description
    # --------------------------------------------------------

    source = source.replace(
        "__ASY_NARRATIVE__",
        escape_asy_string(narrative),
    )

    # --------------------------------------------------------
    # GitHub username
    # --------------------------------------------------------

    source = source.replace(
        "__GITHUB_USERNAME__",
        escape_asy_string(GITHUB_USERNAME),
    )

    # --------------------------------------------------------
    # Repository name
    # --------------------------------------------------------

    source = source.replace(
        "__REPO_NAME__",
        escape_asy_string(REPO_NAME),
    )

    # --------------------------------------------------------
    # Asymptote top section
    # --------------------------------------------------------

    source = source.replace(
        "__ASY_TOP_SECTION__",
        escape_asy_string(top_section),
    )

    # --------------------------------------------------------
    # Asymptote target exam
    # --------------------------------------------------------

    source = source.replace(
        "__ASY_TARGET_EXAM__",
        escape_asy_string(target_exam),
    )

    # --------------------------------------------------------
    # Asymptote mockcard title A
    # --------------------------------------------------------

    source = source.replace(
        "__ASY_MOCKTITLE_A__",
        escape_asy_string(mocktitle_a),
    )

    # --------------------------------------------------------
    # Asymptote mockcard title B
    # --------------------------------------------------------

    source = source.replace(
        "__ASY_MOCKTITLE_B__",
        escape_asy_string(mocktitle_b),
    )

    # --------------------------------------------------------
    # Asymptote mockcard topic
    # --------------------------------------------------------

    source = source.replace(
        "__ASY_MOCKCARD_TOPIC__",
        escape_asy_string(mockcard_topic),
    )

    return source

# ============================================================
# Main
# ============================================================

def main():

    # ========================================================
    # Validate required input files
    # ========================================================

    if not HOMEPAGE_JSON.exists():
        raise FileNotFoundError(
            f"Metadata file not found: {HOMEPAGE_JSON}"
        )

    if not OG_TEMPLATE_FILE.exists():
        raise FileNotFoundError(
            f"OG template not found: {OG_TEMPLATE_FILE}"
        )

    # ========================================================
    # Read generated metadata
    # ========================================================

    data = json.loads(
        HOMEPAGE_JSON.read_text(
            encoding="utf-8"
        )
    )

    # --------------------------------------------------------
    # Read the Asymptote template once.
    #
    # The same template is reused for every content item.
    # --------------------------------------------------------

    template = OG_TEMPLATE_FILE.read_text(
        encoding="utf-8"
    )

    # ========================================================
    # Prepare generated/og/
    # ========================================================

    GENERATED_OG_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ========================================================
    # Counters
    # ========================================================

    generated = 0
    skipped = 0
    warnings = 0

    # ========================================================
    # Generate default OG source
    # ========================================================
    #
    # The default OG image uses only site-wide configuration.
    # It is generated from the same template as page OG images.
    # ========================================================

    default_source = generate_asy(
        template,
        number="",
        top_section=ASY_DEFAULT_TOP_SECTION,
        category="Lecture Notes",#ASY_DEFAULT_TOP_SECTION,
        title="Notes", #ASY_DEFAULT_MOCKTITLE_A,
        narrative=ASY_DEFAULT_NARRATIVE,
        file="",
        tags=[],
        target_exam=ASY_DEFAULT_TARGET_EXAM,
        mocktitle_a=ASY_DEFAULT_MOCKTITLE_A,
        mocktitle_b=ASY_DEFAULT_MOCKTITLE_B,
        mockcard_topic=ASY_DEFAULT_MOCKCARD_TOPIC,
    )

    default_output = GENERATED_OG_DIR / "default.asy"

    default_output.write_text(
        default_source,
        encoding="utf-8",
    )

    print(
        f"📐 Generated "
        f"{default_output.relative_to(ROOT)}"
    )

    # ========================================================
    # Process all content entries
    # ========================================================
    #
    # homepage.json has the following general structure:
    #
    #     {
    #         "Category A": [
    #             {...},
    #             {...}
    #         ],
    #         "Category B": [
    #             {...}
    #         ]
    #     }
    #
    # We intentionally DO NOT check:
    #
    #     lecture.get("type") == "lecture"
    #
    # because not every content page has a `type` field.
    #
    # Instead, the presence of a valid `.typ` source determines
    # whether an entry can have an automatically generated OG
    # image.
    # ========================================================

    for category, pages in data.items():

        # ----------------------------------------------------
        # Process every page/content entry in this category.
        # ----------------------------------------------------

        for page in pages:

            # =================================================
            # Explicit OG image
            # =================================================
            #
            # If the content metadata explicitly supplies:
            #
            #     og_image: "assets/og/fgt1.png"
            #
            # then that image takes precedence.
            #
            # We therefore do NOT create a generated `.asy`
            # source for this page.
            # =================================================

            if page.get("og_image"):

                print(
                    f"⏭️  Skipping "
                    f"{page.get('html', '<unknown>')}"
                    f" — og_image supplied"
                )

                skipped += 1
                continue

            # =================================================
            # Source path
            # =================================================

            source = page.get("source")

            # -------------------------------------------------
            # A content entry without a source cannot be used
            # to determine where its generated OG source should
            # live.
            # -------------------------------------------------

            if not source:

                print(
                    "⚠️  Skipping content entry "
                    "without source"
                )

                warnings += 1
                continue

            # -------------------------------------------------
            # Convert the source into a Path.
            # -------------------------------------------------

            source_path = Path(source)

            # -------------------------------------------------
            # Automatic OG generation currently expects
            # Typst source files.
            # -------------------------------------------------

            if source_path.suffix != ".typ":

                print(
                    f"⚠️  Skipping {source} "
                    f"— expected .typ source"
                )

                warnings += 1
                continue

            # =================================================
            # Determine generated `.asy` path
            # =================================================
            #
            # Preserve the entire source directory structure.
            #
            # Example:
            #
            #     source:
            #         fgt/lec2.typ
            #
            #     output:
            #         generated/og/fgt/lec2.asy
            #
            # Another example:
            #
            #     source:
            #         olympiad/ioqm/ioqm2025.typ
            #
            #     output:
            #         generated/og/olympiad/ioqm/ioqm2025.asy
            # =================================================

            output_relative = source_path.with_suffix(
                ".asy"
            )

            output = (
                GENERATED_OG_DIR
                / output_relative
            )

            # -------------------------------------------------
            # Create any required intermediate directories.
            # -------------------------------------------------

            output.parent.mkdir(
                parents=True,
                exist_ok=True,
            )

            # =================================================
            # Extract metadata for the OG image
            # =================================================

            # -------------------------------------------------
            # Not every page has a number.
            #
            # Use an empty string for pages such as:
            #
            #     MOPSS
            #     IOQM
            #     RMO
            #     course pages
            #     miscellaneous pages
            # -------------------------------------------------

            number = page.get(
                "number",
                "",
            )

            # -------------------------------------------------
            # Every generated OG image should have a title.
            # Use an empty string rather than failing here;
            # metadata validation can handle required metadata.
            # -------------------------------------------------

            title = page.get(
                "title",
                "",
            )

            # -------------------------------------------------
            # Tags associated with this lecture.
            # -------------------------------------------------

            tags = page.get(
                "tags",
                [],
            )

            # -------------------------------------------------
            # The outer dictionary key is the category name.
            # -------------------------------------------------

            category_name = category

            # =================================================
            # Generate Asymptote source
            # =================================================

            source_text = generate_asy(
                template,
                number=number,
                title=title,
                category=category_name,
                file=source_path.stem,
                tags=tags,
                narrative=f"Lectures {number}",
                top_section=ASY_TOP_SECTION,
                target_exam=ASY_TARGET_EXAM,
                mocktitle_a=ASY_MOCKTITLE_A,
                mocktitle_b=ASY_MOCKTITLE_B,
                mockcard_topic=ASY_MOCKCARD_TOPIC,
            )

            # =================================================
            # Write `.asy` file
            # =================================================

            output.write_text(
                source_text,
                encoding="utf-8",
            )

            print(
                f"📐 Generated "
                f"{output.relative_to(ROOT)}"
            )

            generated += 1

    # ========================================================
    # Summary
    # ========================================================

    print()
    print("OG image source generation")
    print("--------------------------")
    print(f"Generated : {generated}")
    print(f"Skipped   : {skipped}")
    print(f"Warnings  : {warnings}")


# ============================================================
# Entry point
# ============================================================

if __name__ == "__main__":
    main()
