#!/usr/bin/env bash

set -euo pipefail

export TYPST_FEATURES=html

# ============================================================
# Configuration
# ============================================================

DIST="dist"

PAGES_DIR="$DIST/pages"
PDF_DIR="$DIST/pdf"
ASSETS_DIR="$DIST/assets"

HOMEPAGE_JSON="generated/homepage.json"

# ============================================================
# Build timing
#
# Record the time at which the build starts.
# The final summary will report the total build time.
# ============================================================

BUILD_START=$(date +%s)

# ============================================================
# Build statistics
#
# These counters are updated during the build and displayed
# in the final build summary.
# ============================================================

CATEGORY_COUNT=0

# ============================================================
# Stage timings
#
# Each major build stage stores its elapsed time so that the
# final summary can show where the build time was spent.
# ============================================================

TIME_METADATA="0"
TIME_METADATA_CHECK="0"
TIME_GENERATED_CHECK="0"
TIME_IMPORT_CHECK="0"
TIME_HTML="0"
TIME_CATEGORIES="0"
TIME_BOOK="0"
TIME_PAGES="0"
TIME_LINKS="0"

# ============================================================
# Diagnostic report paths
#
# These reports are generated by the individual validation
# stages. The final summary reads them without running the
# checks again.
# ============================================================

METADATA_REPORT="diagnostics/metadata_report.txt"
LINK_REPORT="diagnostics/link_report.txt"

# ============================================================
# Helpers
# ============================================================

die() {
    echo "Build failed: $1"
    exit 1
}

# ============================================================
# Timing helpers
#
# Records the start time of a build stage and prints its
# elapsed time when the stage finishes.
# ============================================================

stage_start() {
    STAGE_START=$(date +%s.%N)
}

stage_end() {
    local elapsed
    elapsed=$(awk "BEGIN {printf \"%.2f\", $(date +%s.%N) - $STAGE_START}")
    echo "⏱ $1: ${elapsed}s"
}

# ============================================================
# 1. Generate metadata
# ============================================================

echo "📋 Generating metadata..."

stage_start

python3 scripts/build/generate_metadata.py

TIME_METADATA=$(awk "BEGIN {printf \"%.2f\", $(date +%s.%N) - $STAGE_START}")

stage_end "Metadata generation"

# ============================================================
# 2. Check source metadata
# ============================================================

echo
echo "🔗 Checking source metadata..."

stage_start

if ! python3 scripts/lint/check_metadata.py; then
    die "metadata validation failed."
fi

TIME_METADATA_CHECK=$(awk "BEGIN {printf \"%.2f\", $(date +%s.%N) - $STAGE_START}")

stage_end "Metadata validation"

# ============================================================
# 3. Check generated files
# ============================================================

echo
echo "🔗 Checking generated files..."

stage_start

if ! python3 scripts/lint/check_generated.py; then
    die "generated consistency check failed."
fi

TIME_GENERATED_CHECK=$(awk "BEGIN {printf \"%.2f\", $(date +%s.%N) - $STAGE_START}")

stage_end "Generated-file validation"

# ============================================================
# 4. Check Typst imports
#
# Verify that all imported Typst files exist and that there
# are no circular import dependencies.
#
# The detailed dependency graph is written to:
#
#     diagnostics/imports.dot
#
# ============================================================

echo
echo "🔗 Checking Typst imports..."

stage_start

if ! python3 scripts/lint/check_imports.py; then
    die "Typst import validation failed."
fi

TIME_IMPORT_CHECK=$(awk "BEGIN {printf \"%.2f\", $(date +%s.%N) - $STAGE_START}")

stage_end "Typst import validation"

# ============================================================
# 5. Initialize dist
# ============================================================

echo "📁 Preparing dist/..."

rm -rf "$PAGES_DIR" "$PDF_DIR" "$ASSETS_DIR"

mkdir -p \
    "$PAGES_DIR" \
    "$PDF_DIR" \
    "$ASSETS_DIR/css" \
    "$ASSETS_DIR/js" \
    "$ASSETS_DIR/images"

# ============================================================
# 6. Copy assets
# ============================================================

if [ -f "assets/css/style.css" ]; then

    cp \
        assets/css/style.css \
        "$ASSETS_DIR/css/style.css"

    echo "📋 Copied style.css"

else

    echo "⚠️ Warning: assets/css/style.css not found"

fi

# ============================================================
# 7. Check generated metadata
# ============================================================

if [ ! -f "$HOMEPAGE_JSON" ]; then

    die "Missing $HOMEPAGE_JSON"

fi

# ============================================================
# 8. Generate homepage and compile pages
# ============================================================

echo
echo "🌐 Building course pages..."

stage_start

python3 scripts/build/build_pages.py

TIME_HTML=$(awk "BEGIN {printf \"%.2f\", $(date +%s.%N) - $STAGE_START}")

stage_end "HTML pages"

# ============================================================
# 9. Build category books
# ============================================================

echo
echo "📚 Building category books..."

stage_start

for CATEGORY_SOURCE in generated/category_*.typ; do

    # If no category files exist, skip the loop.
    [ -e "$CATEGORY_SOURCE" ] || continue

    CATEGORY_NAME="$(basename "$CATEGORY_SOURCE" .typ)"

    echo "  📖 Building $CATEGORY_NAME..."

    typst compile \
        --root . \
        "$CATEGORY_SOURCE" \
        "$PDF_DIR/${CATEGORY_NAME}.pdf" \
        --input format=pdf

    # Count successfully compiled category books.
    CATEGORY_COUNT=$((CATEGORY_COUNT + 1))

done

TIME_CATEGORIES=$(awk "BEGIN {printf \"%.2f\", $(date +%s.%N) - $STAGE_START}")

stage_end "Category PDFs"

# ============================================================
# 10. Build complete course PDF
# ============================================================

echo
echo "📚 Building complete course book..."

stage_start

typst compile \
    --root . \
    book_source.typ \
    "$PDF_DIR/book.pdf" \
    --input format=pdf

TIME_BOOK=$(awk "BEGIN {printf \"%.2f\", $(date +%s.%N) - $STAGE_START}")

stage_end "Book PDF"

# ============================================================
# 11. Build complete pages PDF
# ============================================================

echo
echo "📚 Building complete pages.pdf..."

stage_start

typst compile \
    --root . \
    pages_source.typ \
    "$PDF_DIR/pages.pdf" \
    --input format=pdf

TIME_PAGES=$(awk "BEGIN {printf \"%.2f\", $(date +%s.%N) - $STAGE_START}")

stage_end "Pages PDF"

# ============================================================
# 12. Check links
# ============================================================

echo
echo "🔗 Checking links..."

stage_start

if ! python3 scripts/lint/check_links.py; then

    die "broken links detected."

fi

TIME_LINKS=$(awk "BEGIN {printf \"%.2f\", $(date +%s.%N) - $STAGE_START}")

stage_end "Link checking"

# ============================================================
# 13. Build diagnostics summary
#
# The individual reports are still produced at their normal
# stages above. This final section gives a compact overview
# so the build result can be checked without scrolling back.
#
# The existing diagnostic files are read here; the checks are
# NOT executed again.
# ============================================================

BUILD_END=$(date +%s)
BUILD_TIME=$((BUILD_END - BUILD_START))

PAGE_COUNT=$(find "$PAGES_DIR" -type f -name "*.html" | wc -l | tr -d ' ')
PDF_COUNT=$(find "$PDF_DIR" -type f -name "*.pdf" | wc -l | tr -d ' ')

echo
echo "=============================================="
echo "📊 Build diagnostics summary"
echo "=============================================="

# ------------------------------------------------------------
# Metadata report
# ------------------------------------------------------------

if [ -f "$METADATA_REPORT" ]; then

    echo
    echo "## 📋 Metadata"
    echo

    grep -E \
        '^(Total items|Lectures[[:space:]]*:|Pages[[:space:]]*:|Categories[[:space:]]*:)' \
        "$METADATA_REPORT" \
        || true

    echo "Report      : $METADATA_REPORT"

else

    echo
    echo "## 📋 Metadata"
    echo
    echo "Metadata report not found"
fi

# ------------------------------------------------------------
# Link report
# ------------------------------------------------------------

if [ -f "$LINK_REPORT" ]; then

    echo
    echo "## 🔗 Links"
    echo

    grep -E \
        '^(Links checked|Broken links|Working links)' \
        "$LINK_REPORT" \
        || true

    echo "Report      : $LINK_REPORT"

else

    echo
    echo "## 🔗 Links"
    echo
    echo "Link report not found"
fi

# ------------------------------------------------------------
# Build statistics
# ------------------------------------------------------------

echo
echo "## 📦 Build"
echo
echo "🌐 HTML pages:      $PAGE_COUNT"
echo "📚 Category books:  $CATEGORY_COUNT"
echo "📄 PDF files:       $PDF_COUNT"
echo "⏱ Build time:       ${BUILD_TIME}s"

# ------------------------------------------------------------
# Build timing
#
# Shows how much time was spent in each major stage.
# ------------------------------------------------------------

echo
echo "## ⏱ Build timing"
echo
printf "Metadata generation       %6ss\n" "$TIME_METADATA"
printf "Metadata validation       %6ss\n" "$TIME_METADATA_CHECK"
printf "Generated validation      %6ss\n" "$TIME_GENERATED_CHECK"
printf "Typst import validation   %6ss\n" "$TIME_IMPORT_CHECK"
printf "HTML pages                %6ss\n" "$TIME_HTML"
printf "Category PDFs             %6ss\n" "$TIME_CATEGORIES"
printf "Book PDF                  %6ss\n" "$TIME_BOOK"
printf "Pages PDF                 %6ss\n" "$TIME_PAGES"
printf "Link checking             %6ss\n" "$TIME_LINKS"
printf "Total                     %6ss\n" "$BUILD_TIME"

# ------------------------------------------------------------
# Compact one-line summary
#
# Extract the link count from the link report so that the
# final line gives the most useful overall build statistics.
# ------------------------------------------------------------

LINK_COUNT=0
BROKEN_COUNT=0

if [ -f "$LINK_REPORT" ]; then

    LINK_COUNT=$(
        grep '^Links checked' "$LINK_REPORT" |
        awk -F: '{gsub(/[[:space:]]/, "", $2); print $2}'
    )

    BROKEN_COUNT=$(
        grep '^Broken links' "$LINK_REPORT" |
        awk -F: '{gsub(/[[:space:]]/, "", $2); print $2}'
    )

    LINK_COUNT=${LINK_COUNT:-0}
    BROKEN_COUNT=${BROKEN_COUNT:-0}
fi

echo
echo "$PAGE_COUNT HTML · $PDF_COUNT PDFs · $CATEGORY_COUNT categories · $LINK_COUNT links · $BROKEN_COUNT broken"

# ------------------------------------------------------------
# Final status
# ------------------------------------------------------------

echo
echo "=============================================="
echo "✅ Build completed successfully in ${BUILD_TIME}s"
echo "=============================================="