def typst_value(value):
    if value is None:
        return "none"

    if isinstance(value, bool):
        return "true" if value else "false"

    if isinstance(value, list):
        return "[" + ", ".join(typst_value(x) for x in value) + "]"

    if isinstance(value, str):
        if value.startswith("datetime(") and value.endswith(")"):
            return value
        return '"' + value.replace('"', '\\"') + '"'

    return str(value)


def write_field(file, key, value, indent=4):
    """Write one field of a Typst record."""

    spaces = " " * indent

    file.write(
        f"{spaces}{key}: "
        f"{typst_value(value)},\n"
    )


def write_header(file, generated_by):
    """Write the standard header for a generated file."""

    file.write(
        "// ============================================================\n"
        "// GENERATED FILE\n"
        "//\n"
        "// This file is generated by:\n"
        f"//     {generated_by}\n"
        "//\n"
        "// DO NOT EDIT MANUALLY.\n"
        "// ============================================================\n\n"
    )
