"""
Write a human-readable metadata report.

The report is generated from the same metadata objects used by
the rest of the metadata generation pipeline.

Output:

    diagnostics/metadata_report.txt
"""

from collections import defaultdict

from scripts.config import DIAGNOSTICS_DIR


# ============================================================
# Helpers
# ============================================================

def _item_name(item):
    """Return a readable name for a metadata item."""

    title = item.get("title")

    if title:
        return title

    return item.get("file", "Untitled")


def _category(item):
    """Return the item's category."""

    category = item.get("category")

    if isinstance(category, str) and category.strip():
        return category.strip()

    return "Uncategorized"


# ============================================================
# Report
# ============================================================

def write_metadata_report(lectures, pages):
    """
    Write a human-readable metadata report.

    The report contains:

    - overall counts
    - lecture listing
    - page listing
    - category summary
    """

    all_items = list(lectures) + list(pages)

    lines = []

    # ========================================================
    # Header
    # ========================================================

    lines.extend([
        "============================================================\n"
        "GENERATED REPORT\n"
        "\n"
        "This file is generated by:\n"
        "    python3 scripts/run.py metadata\n"
        "\n"
        "DO NOT EDIT MANUALLY.\n"
        "============================================================\n\n"
        "Metadata Report",
        "===============",
        "",
    ])

    # ========================================================
    # Summary
    # ========================================================

    categories = {
        _category(item)
        for item in all_items
    }

    lines.extend([
        "Summary",
        "-------",
        "",
        f"Total items : {len(all_items)}",
        f"Lectures    : {len(lectures)}",
        f"Pages       : {len(pages)}",
        f"Categories  : {len(categories)}",
        "",
    ])

    # ========================================================
    # Lectures
    # ========================================================

    lines.extend([
        "Lectures",
        "--------",
        "",
    ])

    if lectures:

        for item in lectures:

            number = item.get("number")
            title = _item_name(item)
            category = _category(item)
            file_name = item.get("file", "")

            if number is not None:
                label = f"Lecture {number}"
            else:
                label = "Lecture"

            lines.append(
                f"{label}: {title}"
            )

            lines.append(
                f"    file:     {file_name}"
            )

            lines.append(
                f"    category: {category}"
            )

            lines.append("")

    else:

        lines.extend([
            "No lectures.",
            "",
        ])

    # ========================================================
    # Pages
    # ========================================================

    lines.extend([
        "Pages",
        "-----",
        "",
    ])

    if pages:

        for item in pages:

            title = _item_name(item)
            category = _category(item)
            file_name = item.get("file", "")

            lines.append(
                f"{title}"
            )

            lines.append(
                f"    file:     {file_name}"
            )

            lines.append(
                f"    category: {category}"
            )

            lines.append("")

    else:

        lines.extend([
            "No pages.",
            "",
        ])

    # ========================================================
    # Categories
    # ========================================================

    grouped = defaultdict(list)

    for item in all_items:

        grouped[
            _category(item)
        ].append(item)

    lines.extend([
        "Categories",
        "----------",
        "",
    ])

    for category in sorted(grouped):

        items = grouped[category]

        lines.append(
            f"{category} ({len(items)} items)"
        )

        for item in items:

            title = _item_name(item)

            number = item.get("number")

            if number is not None:

                label = f"Lecture {number}: "

            else:

                label = ""

            lines.append(
                f"    - {label}{title}"
            )

        lines.append("")

    # ============================================================
    # Write report
    # ============================================================

    output = DIAGNOSTICS_DIR / "metadata_report.txt"

    DIAGNOSTICS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    output.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    print(
        "Report     : "
        f"📋 Wrote metadata report: {output}"
    )