#!/usr/bin/env python3

"""
Check local links in generated HTML files.

The script:

    1. Scans dist/**/*.html
    2. Checks local href/src links
    3. Ignores external URLs
    4. Writes a human-readable report
    5. Returns non-zero if broken links are found

Report:

    diagnostics/link_report.txt
"""

from pathlib import Path
from html.parser import HTMLParser
from urllib.parse import urlparse, unquote
import sys

from scripts.config import ROOT

DIST = ROOT / "dist"

REPORT_DIR = ROOT / "diagnostics"

REPORT = REPORT_DIR / "link_report.txt"


# ============================================================
# HTML parser
# ============================================================

class LinkParser(HTMLParser):
    """Extract href and src attributes."""

    def __init__(self):
        super().__init__()
        self.links = []

    def handle_starttag(self, tag, attrs):

        for name, value in attrs:

            if name in ("href", "src") and value:
                self.links.append(value)


# ============================================================
# Link handling
# ============================================================

def is_external(link):
    """Return True for links that are not local files."""

    parsed = urlparse(link)

    if parsed.scheme:
        return parsed.scheme in {
            "http",
            "https",
            "mailto",
            "javascript",
            "data",
        }

    if link.startswith("//"):
        return True

    return False


def clean_path(link):
    """Remove query string and fragment."""

    parsed = urlparse(link)

    return unquote(parsed.path)


def resolve_link(source, link):
    """Resolve a local link against its HTML file."""

    path = clean_path(link)

    if not path:
        return None

    if path.startswith("/"):
        return DIST / path.lstrip("/")

    return source.parent / path


# ============================================================
# Check one file
# ============================================================

def check_file(path):
    """
    Check one HTML file.

    Returns:
        checked links
        broken links
        report entries
    """

    parser = LinkParser()

    text = path.read_text(
        encoding="utf-8"
    )

    parser.feed(text)

    checked = 0
    broken = []
    ok = []

    for link in parser.links:

        if is_external(link):
            continue

        if link.startswith("#"):
            continue

        target = resolve_link(
            path,
            link,
        )

        if target is None:
            continue

        checked += 1

        relative_source = path.relative_to(ROOT)

        if target.exists():

            ok.append(
                (
                    relative_source,
                    link,
                    target.relative_to(ROOT),
                )
            )

        else:

            broken.append(
                (
                    relative_source,
                    link,
                    target.relative_to(ROOT),
                )
            )

    return checked, broken, ok


# ============================================================
# Report
# ============================================================

def write_report(
    files_checked,
    links_checked,
    broken,
    ok,
):
    """Write the link-check report."""

    REPORT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    with REPORT.open(
        "w",
        encoding="utf-8",
    ) as file:

        file.write(
            "============================================================\n"
            "GENERATED REPORT\n"
            "\n"
            "This file is generated by:\n"
            "    python3 scripts/run.py links\n"
            "\n"
            "DO NOT EDIT MANUALLY.\n"
            "============================================================\n\n"
            "Link Check Report\n"
        )

        file.write(
            "=================\n\n"
        )

        file.write(
            f"Files checked : {files_checked}\n"
        )

        file.write(
            f"Links checked : {links_checked}\n"
        )

        file.write(
            f"Broken links  : {len(broken)}\n"
        )

        file.write(
            f"Working links : {len(ok)}\n\n"
        )

        # ----------------------------------------------------
        # Broken links
        # ----------------------------------------------------

        file.write(
            "BROKEN LINKS\n"
        )

        file.write(
            "------------\n"
        )

        if broken:

            for source, link, target in broken:

                file.write(
                    f"{source}\n"
                )

                file.write(
                    f"  {link}\n"
                )

                file.write(
                    f"  -> {target} [NOT FOUND]\n\n"
                )

        else:

            file.write(
                "None\n\n"
            )

        # ----------------------------------------------------
        # Working links
        # ----------------------------------------------------

        file.write(
            "WORKING LINKS\n"
        )

        file.write(
            "-------------\n"
        )

        if ok:

            for source, link, target in ok:

                file.write(
                    f"{source}\n"
                )

                file.write(
                    f"  {link}\n"
                )

                file.write(
                    f"  -> {target} [OK]\n\n"
                )

        else:

            file.write(
                "None\n"
            )


# ============================================================
# Main
# ============================================================

def main():

    if not DIST.exists():

        print(
            f"ERROR: {DIST} does not exist."
        )

        return 1

    html_files = sorted(
        DIST.rglob("*.html")
    )

    if not html_files:

        print(
            "ERROR: no HTML files found."
        )

        return 1

    links_checked = 0
    broken = []
    ok = []

    for path in html_files:

        checked, file_broken, file_ok = (
            check_file(path)
        )

        links_checked += checked

        broken.extend(
            file_broken
        )

        ok.extend(
            file_ok
        )

    write_report(
        len(html_files),
        links_checked,
        broken,
        ok,
    )

    # --------------------------------------------------------
    # Console summary
    # --------------------------------------------------------

    print()
    print("🔗 Link check")
    print("=============")

    print(
        f"HTML files : {len(html_files)}"
    )

    print(
        f"Links      : {links_checked}"
    )

    print(
        f"Working    : {len(ok)}"
    )

    print(
        f"Broken     : {len(broken)}"
    )

    print(
        f"Report     : {REPORT}"
    )

    if broken:

        print()
        print(
            "❌ Broken links found."
        )

        return 1

    print()
    print(
        "✅ No broken links found."
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
