#!/usr/bin/env python3

"""
Check consistency between source metadata and generated Typst files.

The actual checking logic is implemented in:

    scripts/lint/generated/

This script is the command-line entry point.

Usage:

    python3 scripts/lint/check_generated.py

Exit status:

    0   generated files are consistent
    1   inconsistencies were found
"""

import sys
from contextlib import redirect_stdout
from io import StringIO

from scripts.config import GENERATED_REPORT

from scripts.lint.generated.source import (
    discover_source_metadata,
)

from scripts.lint.generated.checks import (
    check_lectures,
    check_pages,
    check_category_books,
)

from scripts.lint.generated.report import (
    display_path,
)


# ============================================================
# Main check
# ============================================================

def run_check():

    (
        wrappers,
        lectures,
        pages,
        errors,
    ) = discover_source_metadata()

    # --------------------------------------------------------
    # All metadata-bearing content
    #
    # Category books are generated from both lectures and
    # pages, so the consistency check must use the same set.
    # --------------------------------------------------------

    all_content = lectures + pages

    # --------------------------------------------------------
    # Generated consistency
    # --------------------------------------------------------

    check_lectures(
        lectures,
        errors,
    )

    check_pages(
        pages,
        errors,
    )

    check_category_books(
        all_content,
        errors,
    )

    return (
        wrappers,
        lectures,
        pages,
        errors,
    )


# ============================================================
# Report
# ============================================================

def make_report(
    wrappers,
    lectures,
    pages,
    errors,
):
    """
    Build the human-readable generated consistency report.
    """

    output = StringIO()

    with redirect_stdout(output):

        print()
        print("==============================")
        print("Generated Consistency Check")
        print("==============================")
        print()

        print(
            f"Source wrappers : {len(wrappers)}"
        )

        print(
            f"Source metadata : {len(wrappers)}"
        )

        print(
            f"Lectures        : {len(lectures)}"
        )

        print(
            f"Pages           : {len(pages)}"
        )

        print(
            f"Errors          : {len(errors)}"
        )

        # ----------------------------------------------------
        # Errors
        # ----------------------------------------------------

        if errors:

            print()
            print("==============================")
            print("Generated Consistency Errors")
            print("==============================")
            print()

            for path, message in errors:

                print(
                    display_path(path)
                )

                print(
                    f"   -> {message}"
                )

                print()

            print(
                "Generated consistency check failed."
            )

        # ----------------------------------------------------
        # Success
        # ----------------------------------------------------

        else:

            print()
            print(
                "No generated consistency errors found."
            )

            print()
            print(
                "Generated consistency check passed."
            )

    return output.getvalue()


# ============================================================
# Main
# ============================================================

def main():

    (
        wrappers,
        lectures,
        pages,
        errors,
    ) = run_check()

    report = make_report(
        wrappers,
        lectures,
        pages,
        errors,
    )

    # --------------------------------------------------------
    # Write diagnostic report
    # --------------------------------------------------------

    GENERATED_REPORT.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    GENERATED_REPORT.write_text(
        "============================================================\n"
        "GENERATED REPORT\n"
        "\n"
        "This file is generated by:\n"
        "    python3 scripts/run.py generated\n"
        "\n"
        "DO NOT EDIT MANUALLY.\n"
        "============================================================\n\n"
        + report,
        encoding="utf-8",
    )

    # --------------------------------------------------------
    # Display the same report in the terminal
    # --------------------------------------------------------

    print(report, end="")

    # --------------------------------------------------------
    # Exit status
    # --------------------------------------------------------

    if errors:
        return 1

    return 0


# ============================================================
# Entry point
# ============================================================

if __name__ == "__main__":
    sys.exit(main())